title: My Docs Site
theme: minima
markdown: kramdown
baseurl: "/my-docs"

collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
