name: Deploy Preview (develop)

on:
  push:
    branches: [develop]

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll + minima and build
        run: |
          gem install jekyll:4.3.2 bundler:2.4.22 minima:2.5.1 jekyll-remote-theme:0.4.3 jekyll-sass-converter:3.0.0
          echo "theme: minima" > _config_theme.yml
          jekyll build --config _config.yml,_config_theme.yml,_config_preview.yml -d _site
          touch _site/.nojekyll


      - name: Deploy to gh-pages/preview/
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          destination_dir: preview
