name: Manual Doc Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release folder (e.g., doc-0.0.1)'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll and minima theme
        run: |
          gem install jekyll bundler minima
          echo "theme: minima" > _config_theme.yml
          cat <<EOF > _config_release.yml
          baseurl: "/my-docs/${{ github.event.inputs.version }}"
          EOF
          jekyll build --config _config.yml,_config_theme.yml,_config_release.yml -d _site
          touch _site/.nojekyll

      - name: Add root redirect to built site
        run: |
          echo '<meta http-equiv="refresh" content="0; url=./${{ github.event.inputs.version }}/">' > _site/index.html

      - name: Deploy full site with redirect in one commit
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          destination_dir: .
          keep_files: true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Docs ${{ github.event.inputs.version }}
          body: |
            🗂️ View the documentation at:
            👉 https://raimundasr.github.io/my-docs/${{ github.event.inputs.version }}/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}